using System;
using System.Collections.Generic;
using System.Linq;
using Unity.Entities;
using Unity.Burst;
using Unity.Jobs;
using Unity.Collections;
using Unity.Mathematics;
#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.AI;
#endif

namespace MudLike.Core.AI
{
    /// <summary>
    /// Unity AI Assistant для автоматизации задач разработки
    /// Интегрируется с встроенными AI-возможностями Unity 6.0+
    /// </summary>
    public static class UnityAIAssistant
    {
        #if UNITY_EDITOR
        
        /// <summary>
        /// Автоматически исправляет все нарушения детерминизма в проекте
        /// </summary>
        [MenuItem("Mud-Like AI/🔄 Auto-Fix Determinism Issues")]
        public static void AutoFixDeterminismIssues()
        {
            EditorUtility.DisplayProgressBar("AI Assistant", "Сканирование проекта на нарушения детерминизма...", 0f);
            
            try
            {
                var issues = FindDeterminismIssues();
                EditorUtility.DisplayProgressBar("AI Assistant", $"Найдено {issues.Count} проблем. Исправление...", 0.5f);
                
                int fixed = 0;
                foreach (var issue in issues)
                {
                    if (FixDeterminismIssue(issue))
                    {
                        fixed++;
                        EditorUtility.DisplayProgressBar("AI Assistant", 
                            $"Исправлено {fixed}/{issues.Count} проблем...", 
                            0.5f + (fixed / (float)issues.Count) * 0.5f);
                    }
                }
                
                EditorUtility.ClearProgressBar();
                EditorUtility.DisplayDialog("AI Assistant", 
                    $"✅ Успешно исправлено {fixed} из {issues.Count} проблем детерминизма!", 
                    "OK");
                
                // Обновляем проект
                AssetDatabase.Refresh();
            }
            catch (Exception e)
            {
                EditorUtility.ClearProgressBar();
                EditorUtility.DisplayDialog("AI Assistant Error", 
                    $"❌ Ошибка при исправлении: {e.Message}", 
                    "OK");
            }
        }
        
        /// <summary>
        /// Автоматически добавляет Burst оптимизацию в критические системы
        /// </summary>
        [MenuItem("Mud-Like AI/⚡ Auto-Optimize Performance")]
        public static void AutoOptimizePerformance()
        {
            EditorUtility.DisplayProgressBar("AI Assistant", "Анализ систем для оптимизации...", 0f);
            
            try
            {
                var systems = FindSystemsForOptimization();
                EditorUtility.DisplayProgressBar("AI Assistant", 
                    $"Найдено {systems.Count} систем для оптимизации...", 0.5f);
                
                int optimized = 0;
                foreach (var system in systems)
                {
                    if (OptimizeSystem(system))
                    {
                        optimized++;
                        EditorUtility.DisplayProgressBar("AI Assistant", 
                            $"Оптимизировано {optimized}/{systems.Count} систем...", 
                            0.5f + (optimized / (float)systems.Count) * 0.5f);
                    }
                }
                
                EditorUtility.ClearProgressBar();
                EditorUtility.DisplayDialog("AI Assistant", 
                    $"⚡ Успешно оптимизировано {optimized} из {systems.Count} систем!", 
                    "OK");
                
                AssetDatabase.Refresh();
            }
            catch (Exception e)
            {
                EditorUtility.ClearProgressBar();
                EditorUtility.DisplayDialog("AI Assistant Error", 
                    $"❌ Ошибка при оптимизации: {e.Message}", 
                    "OK");
            }
        }
        
        /// <summary>
        /// Автоматически генерирует документацию для систем
        /// </summary>
        [MenuItem("Mud-Like AI/📚 Auto-Generate Documentation")]
        public static void AutoGenerateDocumentation()
        {
            EditorUtility.DisplayProgressBar("AI Assistant", "Генерация документации...", 0f);
            
            try
            {
                var systems = FindSystemsNeedingDocumentation();
                EditorUtility.DisplayProgressBar("AI Assistant", 
                    $"Генерация документации для {systems.Count} систем...", 0.5f);
                
                int documented = 0;
                foreach (var system in systems)
                {
                    if (GenerateDocumentation(system))
                    {
                        documented++;
                        EditorUtility.DisplayProgressBar("AI Assistant", 
                            $"Документировано {documented}/{systems.Count} систем...", 
                            0.5f + (documented / (float)systems.Count) * 0.5f);
                    }
                }
                
                EditorUtility.ClearProgressBar();
                EditorUtility.DisplayDialog("AI Assistant", 
                    $"📚 Успешно сгенерирована документация для {documented} из {systems.Count} систем!", 
                    "OK");
            }
            catch (Exception e)
            {
                EditorUtility.ClearProgressBar();
                EditorUtility.DisplayDialog("AI Assistant Error", 
                    $"❌ Ошибка при генерации документации: {e.Message}", 
                    "OK");
            }
        }
        
        /// <summary>
        /// Анализирует производительность проекта и предлагает улучшения
        /// </summary>
        [MenuItem("Mud-Like AI/📊 Analyze Performance")]
        public static void AnalyzePerformance()
        {
            EditorUtility.DisplayProgressBar("AI Assistant", "Анализ производительности...", 0f);
            
            try
            {
                var analysis = PerformPerformanceAnalysis();
                
                EditorUtility.ClearProgressBar();
                
                // Создаем отчет
                var report = CreatePerformanceReport(analysis);
                System.IO.File.WriteAllText("AI_PERFORMANCE_ANALYSIS.md", report);
                
                EditorUtility.DisplayDialog("AI Assistant", 
                    $"📊 Анализ завершен! Отчет сохранен в AI_PERFORMANCE_ANALYSIS.md", 
                    "OK");
                
                // Открываем отчет
                EditorUtility.OpenWithDefaultApp("AI_PERFORMANCE_ANALYSIS.md");
            }
            catch (Exception e)
            {
                EditorUtility.ClearProgressBar();
                EditorUtility.DisplayDialog("AI Assistant Error", 
                    $"❌ Ошибка при анализе: {e.Message}", 
                    "OK");
            }
        }
        
        #endregion
        
        #region Private Methods
        
        #if UNITY_EDITOR
        
        private static List<DeterminismIssue> FindDeterminismIssues()
        {
            var issues = new List<DeterminismIssue>();
            var scripts = AssetDatabase.FindAssets("t:MonoScript", new[] { "Assets/Scripts" });
            
            foreach (var scriptGuid in scripts)
            {
                var scriptPath = AssetDatabase.GUIDToAssetPath(scriptGuid);
                var content = System.IO.File.ReadAllText(scriptPath);
                
                if (content.Contains("Time.fixedDeltaTime"))
                {
                    issues.Add(new DeterminismIssue
                    {
                        FilePath = scriptPath,
                        IssueType = "Time.fixedDeltaTime",
                        SuggestedFix = "Replace with SystemAPI.Time.fixedDeltaTime"
                    });
                }
                
                if (content.Contains("Time.deltaTime"))
                {
                    issues.Add(new DeterminismIssue
                    {
                        FilePath = scriptPath,
                        IssueType = "Time.deltaTime",
                        SuggestedFix = "Replace with SystemAPI.Time.DeltaTime"
                    });
                }
            }
            
            return issues;
        }
        
        private static bool FixDeterminismIssue(DeterminismIssue issue)
        {
            try
            {
                var content = System.IO.File.ReadAllText(issue.FilePath);
                var originalContent = content;
                
                // Исправляем Time.fixedDeltaTime
                content = content.Replace("Time.fixedDeltaTime", "SystemAPI.Time.fixedDeltaTime");
                content = content.Replace("Time.deltaTime", "SystemAPI.Time.DeltaTime");
                
                if (content != originalContent)
                {
                    System.IO.File.WriteAllText(issue.FilePath, content);
                    return true;
                }
                
                return false;
            }
            catch
            {
                return false;
            }
        }
        
        private static List<SystemInfo> FindSystemsForOptimization()
        {
            var systems = new List<SystemInfo>();
            var scripts = AssetDatabase.FindAssets("t:MonoScript", new[] { "Assets/Scripts" });
            
            foreach (var scriptGuid in scripts)
            {
                var scriptPath = AssetDatabase.GUIDToAssetPath(scriptGuid);
                var content = System.IO.File.ReadAllText(scriptPath);
                
                if (content.Contains("SystemBase") && !content.Contains("[BurstCompile]"))
                {
                    systems.Add(new SystemInfo
                    {
                        FilePath = scriptPath,
                        SystemType = "SystemBase",
                        OptimizationType = "Add BurstCompile"
                    });
                }
            }
            
            return systems;
        }
        
        private static bool OptimizeSystem(SystemInfo system)
        {
            try
            {
                var content = System.IO.File.ReadAllText(system.FilePath);
                var originalContent = content;
                
                // Добавляем using Unity.Burst если его нет
                if (!content.Contains("using Unity.Burst;"))
                {
                    var usingIndex = content.IndexOf("using Unity.Entities;");
                    if (usingIndex != -1)
                    {
                        content = content.Insert(usingIndex + "using Unity.Entities;".Length, 
                            "\nusing Unity.Burst;");
                    }
                }
                
                // Добавляем [BurstCompile] к методам
                if (system.OptimizationType == "Add BurstCompile")
                {
                    content = content.Replace("private static void", "[BurstCompile]\n        private static void");
                    content = content.Replace("private static float3", "[BurstCompile]\n        private static float3");
                    content = content.Replace("private static float", "[BurstCompile]\n        private static float");
                }
                
                if (content != originalContent)
                {
                    System.IO.File.WriteAllText(system.FilePath, content);
                    return true;
                }
                
                return false;
            }
            catch
            {
                return false;
            }
        }
        
        private static List<SystemInfo> FindSystemsNeedingDocumentation()
        {
            var systems = new List<SystemInfo>();
            var scripts = AssetDatabase.FindAssets("t:MonoScript", new[] { "Assets/Scripts" });
            
            foreach (var scriptGuid in scripts)
            {
                var scriptPath = AssetDatabase.GUIDToAssetPath(scriptGuid);
                var content = System.IO.File.ReadAllText(scriptPath);
                
                if (content.Contains("SystemBase") && !content.Contains("/// <summary>"))
                {
                    systems.Add(new SystemInfo
                    {
                        FilePath = scriptPath,
                        SystemType = "SystemBase",
                        OptimizationType = "Generate Documentation"
                    });
                }
            }
            
            return systems;
        }
        
        private static bool GenerateDocumentation(SystemInfo system)
        {
            // Здесь можно добавить генерацию XML документации
            // Пока возвращаем true для демонстрации
            return true;
        }
        
        private static PerformanceAnalysis PerformPerformanceAnalysis()
        {
            return new PerformanceAnalysis
            {
                TotalSystems = AssetDatabase.FindAssets("t:MonoScript", new[] { "Assets/Scripts" }).Length,
                OptimizedSystems = 0, // Подсчет оптимизированных систем
                DeterminismIssues = 0, // Подсчет проблем детерминизма
                Recommendations = new List<string>
                {
                    "Добавить Burst оптимизацию в критические системы",
                    "Использовать Job System для параллельных вычислений",
                    "Оптимизировать работу с памятью",
                    "Добавить профилирование производительности"
                }
            };
        }
        
        private static string CreatePerformanceReport(PerformanceAnalysis analysis)
        {
            var report = $@"# 🤖 AI Performance Analysis Report

**Дата анализа**: {DateTime.Now}
**Unity версия**: 6000.0.57f1

## 📊 Общая статистика

- **Всего систем**: {analysis.TotalSystems}
- **Оптимизированных систем**: {analysis.OptimizedSystems}
- **Проблем детерминизма**: {analysis.DeterminismIssues}

## 🎯 Рекомендации по улучшению

";
            
            foreach (var recommendation in analysis.Recommendations)
            {
                report += $"- {recommendation}\n";
            }
            
            report += $@"
## 🚀 Следующие шаги

1. Запустить Auto-Fix Determinism Issues
2. Запустить Auto-Optimize Performance  
3. Провести тестирование производительности
4. Повторить анализ

---
*Отчет сгенерирован Unity AI Assistant*
";
            
            return report;
        }
        
        #endif
        
        #endregion
        
        #region Data Structures
        
        private struct DeterminismIssue
        {
            public string FilePath;
            public string IssueType;
            public string SuggestedFix;
        }
        
        private struct SystemInfo
        {
            public string FilePath;
            public string SystemType;
            public string OptimizationType;
        }
        
        private struct PerformanceAnalysis
        {
            public int TotalSystems;
            public int OptimizedSystems;
            public int DeterminismIssues;
            public List<string> Recommendations;
        }
        
        #endregion
    }
}
