using System;
using System.Collections.Generic;
using Unity.Entities;
using UnityEngine;

namespace MudLike.Core.AI
{
    /// <summary>
    /// Конфигурация для AI-агентов проекта Mud-Like
    /// Настраивает поведение и приоритеты автоматических задач
    /// </summary>
    [CreateAssetMenu(fileName = "AIAgentConfig", menuName = "Mud-Like/AI Agent Config")]
    public class AIAgentConfig : ScriptableObject
    {
        [Header("🤖 AI Agent Settings")]
        [Tooltip("Включить автоматическую шлифовку проекта")]
        public bool EnableAutoPolishing = true;
        
        [Tooltip("Включить автоматическое исправление ошибок")]
        public bool EnableAutoFixing = true;
        
        [Tooltip("Включить автоматическую оптимизацию")]
        public bool EnableAutoOptimization = true;
        
        [Header("⚡ Performance Settings")]
        [Tooltip("Автоматически добавлять Burst оптимизацию")]
        public bool AutoAddBurstCompile = true;
        
        [Tooltip("Автоматически исправлять детерминизм")]
        public bool AutoFixDeterminism = true;
        
        [Tooltip("Автоматически оптимизировать память")]
        public bool AutoOptimizeMemory = false;
        
        [Header("📚 Documentation Settings")]
        [Tooltip("Автоматически генерировать документацию")]
        public bool AutoGenerateDocumentation = true;
        
        [Tooltip("Автоматически обновлять README")]
        public bool AutoUpdateReadme = false;
        
        [Header("🔍 Validation Settings")]
        [Tooltip("Строгость валидации кода")]
        public ValidationLevel ValidationLevel = ValidationLevel.Strict;
        
        [Tooltip("Автоматически исправлять найденные проблемы")]
        public bool AutoFixValidationIssues = true;
        
        [Header("📊 Reporting Settings")]
        [Tooltip("Создавать отчеты о работе")]
        public bool GenerateReports = true;
        
        [Tooltip("Уровень детализации отчетов")]
        public ReportDetailLevel ReportDetailLevel = ReportDetailLevel.Detailed;
        
        [Header("⏰ Scheduling Settings")]
        [Tooltip("Запускать проверки автоматически")]
        public bool EnableAutoScheduling = false;
        
        [Tooltip("Интервал проверок (в минутах)")]
        [Range(5, 1440)]
        public int CheckIntervalMinutes = 60;
        
        [Header("🎯 Task Priorities")]
        [Tooltip("Приоритет задач детерминизма")]
        public TaskPriority DeterminismPriority = TaskPriority.Critical;
        
        [Tooltip("Приоритет задач производительности")]
        public TaskPriority PerformancePriority = TaskPriority.High;
        
        [Tooltip("Приоритет задач документации")]
        public TaskPriority DocumentationPriority = TaskPriority.Medium;
        
        [Header("📁 File Patterns")]
        [Tooltip("Паттерны файлов для анализа")]
        public List<string> AnalysisFilePatterns = new List<string>
        {
            "*.cs",
            "*.asmdef",
            "*.meta"
        };
        
        [Tooltip("Исключаемые папки")]
        public List<string> ExcludeFolders = new List<string>
        {
            "Library",
            "Temp",
            "Logs",
            "UserSettings"
        };
        
        [Header("🔧 Advanced Settings")]
        [Tooltip("Максимальное количество параллельных задач")]
        [Range(1, 10)]
        public int MaxConcurrentTasks = 3;
        
        [Tooltip("Таймаут выполнения задач (в секундах)")]
        [Range(10, 300)]
        public int TaskTimeoutSeconds = 60;
        
        [Tooltip("Уровень логирования")]
        public LogLevel LogLevel = LogLevel.Info;
        
        /// <summary>
        /// Получить настройки по умолчанию
        /// </summary>
        public static AIAgentConfig GetDefaultConfig()
        {
            var config = CreateInstance<AIAgentConfig>();
            return config;
        }
        
        /// <summary>
        /// Проверить, включена ли функция
        /// </summary>
        public bool IsFeatureEnabled(string featureName)
        {
            return featureName switch
            {
                "AutoPolishing" => EnableAutoPolishing,
                "AutoFixing" => EnableAutoFixing,
                "AutoOptimization" => EnableAutoOptimization,
                "BurstCompile" => AutoAddBurstCompile,
                "Determinism" => AutoFixDeterminism,
                "Memory" => AutoOptimizeMemory,
                "Documentation" => AutoGenerateDocumentation,
                "Readme" => AutoUpdateReadme,
                "Reports" => GenerateReports,
                "Scheduling" => EnableAutoScheduling,
                _ => false
            };
        }
        
        /// <summary>
        /// Получить приоритет задачи
        /// </summary>
        public TaskPriority GetTaskPriority(string taskType)
        {
            return taskType switch
            {
                "Determinism" => DeterminismPriority,
                "Performance" => PerformancePriority,
                "Documentation" => DocumentationPriority,
                _ => TaskPriority.Medium
            };
        }
    }
    
    /// <summary>
    /// Уровни валидации
    /// </summary>
    public enum ValidationLevel
    {
        Relaxed,    // Минимальная проверка
        Standard,   // Стандартная проверка
        Strict,     // Строгая проверка
        Extreme     // Максимальная проверка
    }
    
    /// <summary>
    /// Уровни детализации отчетов
    /// </summary>
    public enum ReportDetailLevel
    {
        Minimal,    // Минимальная информация
        Standard,   // Стандартная информация
        Detailed,   // Подробная информация
        Verbose     // Максимальная детализация
    }
    
    /// <summary>
    /// Приоритеты задач
    /// </summary>
    public enum TaskPriority
    {
        Critical,   // Критический
        High,       // Высокий
        Medium,     // Средний
        Low         // Низкий
    }
    
    /// <summary>
    /// Уровни логирования
    /// </summary>
    public enum LogLevel
    {
        Error,      // Только ошибки
        Warning,    // Ошибки и предупреждения
        Info,       // Информационные сообщения
        Debug       // Отладочная информация
    }
}
